"""Declarative base + shared column helpers.

The SQL migration in migrations/ is the schema's source of truth; these models
must stay in sync with it (they are mapped to, not generators of, the DDL).
"""
import uuid
from datetime import datetime

from sqlalchemy import DateTime, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func


class Base(DeclarativeBase):
    pass


def uuid_pk() -> Mapped[uuid.UUID]:
    """UUID primary key generated by Postgres (pgcrypto gen_random_uuid)."""
    return mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )


class TimestampMixin:
    """created_at + updated_at. updated_at is maintained by the DB trigger
    touch_updated_at(); onupdate covers ORM-issued UPDATEs symmetrically."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        server_default=func.now(), onupdate=func.now(),
    )
